name: Audit

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Cache bundler
        uses: actions/cache@v1
        env:
          cache-version: v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ env.cache-version }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-${{ env.cache-version }}-
            ${{ runner.os }}-bundler-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path vendor/bundle
          bundle check || bundle install --deployment

      - name: Audit gems
        run: bundle exec bundle audit check --update

  npm-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache npm
        uses: actions/cache@v1
        env:
          cache-version: v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-version }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Audit npm
        run: npm audit

  yarn-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache yarn
        uses: actions/cache@v1
        env:
          cache-version: v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ env.cache-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.cache-version }}-
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --check-files --cache-folder ~/.cache/yarn

      - name: Audit yarn
        run: yarn audit